### ISSUE TITLE
AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by mvrozanti** [petertodd/timelock#4]
https://stackoverflow.com/questions/58569361/attributeerror-module-time-has-no-attribute-clock-in-python-3-8

```
INFO:root:Benchmarking kernel 'python'
Traceback (most recent call last):
  File "./timelock.py", line 304, in <module>
    args.cmd_func(args)
  File "./timelock.py", line 58, in cmd_benchmark
    run_results[kernel] = kernel.benchmark(args.runtime, args.n)
  File "/home/nexor/util/timelock/timelock/kernel.py", line 83, in benchmark
    start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
```

This happens for python 3.8

**Comment by mvrozanti** [comment]
I'm not sure if this is supposed to [run on Linux or Windows](https://docs.python.org/3.7/library/time.html?highlight=time%20clock#time.clock) so I'm not sure what to replace it with.

**Comment by igorhvr** [comment]
This is addressed by https://github.com/petertodd/timelock/pull/5 ..

**Comment by petertodd** [comment]
Fixed!
